### ISSUE TITLE
Older PyPI releases link to malware?

### ISSUE THREAD

**Issue by jamadden** [bialix/intelhex#17]
Hi, I help support the PyPI server software by answering bug reports. We've [recently been told](https://github.com/pypa/pypi-legacy/issues/694) that some of the older releases of this project (1.5 and below, I think) have a "Home Page" URL specified that points to a compromised server that is deploying malware. 

Could you please check that out? If true, since it's not possible to edit older releases anymore, then if the server cannot be fixed, the only option may be to remove those older releases.

Thank you.

**Comment by bialix** [comment]
@jpwright Thank you for info, I will remove those older releases. That was my old home page which is not my page for many years now.

**Comment by jamadden** [comment]
@bialix Thanks for your quick response! The older releases have been removed. (I was sloppy with my wording, 1.5 doesn't seem affected.)

**Comment by bialix** [comment]
I've just removed all releases past 1.5. But I keep 1.5 release for now, because I don't see any links to my old home page. If there any problems with 1.5 just letting me know.

Related issue https://github.com/pypa/pypi-legacy/issues/694 was also closed now.
