### ISSUE TITLE
python3 gets wrong data type

### ISSUE THREAD

**Issue by ali65** [bialix/intelhex#18]
`>>> sys.version_info`
`sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)`
`>>> import intelhex`
`>>> myhex = intelhex.IntelHex('/home/albert/albert.kurucz/MultiRadio/trunk RF200_AES128_SnapV2.8.2.hex')`
`>>> myhex.segments()`
`[(0, 420), (752, 761), (3072, 3360), (65536, 122354), (128256, 128562), (128682, 128690), (128698, 128934)]`
`>>> data=myhex.gets(0, 420)`
`>>> type(data)`
`<class 'str'>`

**with python3 expected data type returned by gets is <class 'bytes'> not <class 'str'>**

intelhex==2.1

**Comment by ali65** [comment]
Attached please find my test hex file.
[RF200_AES128_SnapV2.8.2.hex.tar.gz](https://github.com/bialix/intelhex/files/1621228/RF200_AES128_SnapV2.8.2.hex.tar.gz)

**Comment by bialix** [comment]
Please make simple test:

```
>>> import array
>>> a = array.array('B', b'12345678')
>>> a.tobytes()
>>> print(type(_))
>>> from intelhex import compat
>>> print(compat.array_tobytes)
>>> compat.array_tobytes(a)
>>> print(type(_))
```

And tell me results from your machine.

**Comment by ali65** [comment]
albert@albertx:~$ python3.5
Python 3.5.3+ (default, Nov 29 2017, 08:55:08)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> a = array.array('B', b'12345678')
>>> a.tobytes()
b'12345678'
>>> print(type(_))
<class 'bytes'>
>>> from intelhex import compat
>>> print(compat.array_tobytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'intelhex.compat' has no attribute 'array_tobytes'
>>> compat.array_tobytes(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'intelhex.compat' has no attribute 'array_tobytes'
>>> print(type(_))
<class 'bytes'>
>>>

**Comment by bialix** [comment]
OK, I see, that has been already fixed in master post 2.1. Can you use version from github?
That should work:

`pip install -U --pre https://github.com/bialix/intelhex/archive/master.zip`

**Comment by ali65** [comment]
OK, the "pre" release have fixed the issue.
When can I see a fixed release? Big thanks for the quick response!

albert@albertx:~$ sudo -H python3 -m pip install -U --pre
https://github.com/bialix/intelhex/archive/master.zip
[sudo] password for albert:
Collecting https://github.com/bialix/intelhex/archive/master.zip
  Downloading https://github.com/bialix/intelhex/archive/master.zip
     \ 102kB 1.0MB/s
Installing collected packages: intelhex
  Found existing installation: intelhex 2.1
    Uninstalling intelhex-2.1:
      Successfully uninstalled intelhex-2.1
  Running setup.py install for intelhex ... done
Successfully installed intelhex-2.1
albert@albertx:~$ python3
Python 3.5.3+ (default, Nov 29 2017, 08:55:08)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import intelhex
>>> myhex =
intelhex.IntelHex('/home/albert/albert.kurucz/MultiRadio/trunk/RF200_AES128_SnapV2.8.2.hex')
>>> data=myhex.gets(0, 420)
>>> type(data)
<class 'bytes'>
>>>

**Comment by bialix** [comment]
I can't promise for any specific date, but I'll try to roll release in next few weeks.
