### ISSUE TITLE
Write hex file with chooseable byte count

### ISSUE THREAD

**Issue by erki1993** [bialix/intelhex#9]
At the moment the only possible data field byte count is 16 when using write_hex_file.

Intelhex wiki: The maximum byte count is 255 (0xFF). 16 (0x10) and 32 (0x20) are commonly used byte counts. 

Should be able to choose variable byte_count ranging from 1 to 255 when writing the hex file.

**Comment by wexi** [comment]
It's indeed a useful feature. To increase Flash uploading speed I made the following simple patch:
[diff.txt](https://github.com/bialix/intelhex/files/832254/diff.txt)
May I suggest incorporating this, raising an exception perhaps if the new data_rec_len is outside range.

Thanks, Enoch.

**Comment by Martoni** [comment]
@wexi, [Your patch ](https://github.com/Martoni/intelhex/commit/aa866d127245821ead2026e8aa62fc6fe1a80725)works for me.

**Comment by bialix** [comment]
@erki1993 Thanks, your patch is merged now.
